### PR TITLE
Implement Debug for base64::Config

### PR DESCRIPTION
**Pull request by programble**

### CODE REVIEW

**Comment by programble** [comment]
What should be the course of action here? I don't mind removing the Debug impl for Encoder to maintain backwards compatibility.

**Comment by alexcrichton** [comment]
Was there some particular motivation for this? Some of these seem a little odd to have `Debug` implementations?

**Comment by programble** [comment]
I wanted `Debug` on the `base64::Config` since I have a struct that holds one in a project of mine. I figured I could add `Debug` implementations everywhere else while I was at it, just in case. I'm fine with removing the implementations on the other types if you'd rather not have them.

**Comment by alexcrichton** [comment]
Ok, let's stick to just the base64 ones for now?

**Comment by programble** [comment]
Done.

**Comment by alexcrichton** [comment]
Thanks!

**Pull request merged**
