### PR TITLE
Add capacity bounds to `read_map` and `read_seq`.

### PR DESCRIPTION
**Pull request by TyOverby**
This is a solution to https://github.com/rust-lang/rustc-serialize/issues/115

It is a breaking change, but will only break people that implement their own `Decoders`, not everyone that uses Decodables.

### CODE REVIEW

**Comment by BurntSushi** [comment]
I'm good with this unless someone has a better idea!

**Comment by alexcrichton** [comment]
I'm personally quite wary to make this minor of a breaking change to rustc-serialize without possibly scheduling some other changes. This crate is one of the most download crates on crates.io, and pushing the whole ecosystem to use a newer major version would be quite an effort, and different versions of rustc-serialize often lead to havoc and type errors. Basically I would just predict that the cost of a breaking change to rustc-serialize is fairly high today, and the wins from this may not be worth the payoff?

**Comment by BurntSushi** [comment]
That's a good point. Definitely not a decision to make lightly.

If I understand right, I think the downside of not merging this is that performant binary decoders that accept untrusted data can never be written with `rustc-serialize`. Maybe that's OK if we're all going to move to serde at some point (soon).

**Comment by alexcrichton** [comment]
So I think I also don't quite understand the underlying issue here, which may help to understand as well. @TyOverby can you go into a little more detail about how this fixes the problem? For example the implementation of `Decoder` for JSON here just passes `len, len`, which your issue claims is bad for untrusted inputs, but how would, for example, bincode implement this differently? Where do you get a "trusted" capacity from?

**Comment by TyOverby** [comment]
The original bug (opened in `bincode`) is [here](https://github.com/TyOverby/bincode/issues/41)
I remembered @BurntSushi's binary decoder and reproduced it for cbor [here](https://github.com/BurntSushi/rust-cbor/pull/4/files)

@BurntSushi managed to write a fix for his slow decoder (it first parses the data into an intermediate form, then it does decoding on that), but he can't fix it for his fast decoder (decodes straight from binary form).  

The reason that JSON is different is because (similarly to @BurntSushi's slow decoder), it is decoding from an already-in-memory value.  This means that sanitization would have already occurred at that point.

However, for Bincode and for CBOR's fast parser -- if we were decoding off of a TCP stream for example -- we read out the "length" of an seq or map before we do any more reads from the TCP stream.  Currently, we pass that length back in through the given `read_seq` closure, and the length is used by collections as both "number of times to call `read_seq_elt`" and "use for the capacity".  

The problem is that Bincode and CBOR have no other chance but to trust the user input, which means that you can crash CBOR with 

```rust
let bad = vec![155u8, 0x00, 0xFF, 0xFF, 0xFF, 0x00, 0xFF, 0xFF, 0xFF];
let _: Vec<u32> = decode(&bad[..]);  // Vec pre-allocates 0xFFFFFF00FFFFFF bytes.
```

And you can crash Bincode with 

```rust
let x = encode(&FakeVec { len: 0xffffffffffffffffu64, byte: 1 }, Bounded(10)).unwrap();
let y : Result<Vec<u8>, _> = decode_from(&mut Cursor::new(&x[..]), Bounded(10));
```

A "proper" streaming binary decoder would let the user configure the pre-allocation size that it would pass into Decodables, but it could also have a sane default.  

I don't have any real doubts that this pull request "should" be merged; using length as an estimated capacity isn't good when dealing with untrusted input.  However, I wouldn't mind waiting until more breaking changes are proposed before merging them.  That said, I think the community is robust enough to handle another change.  Besides, the crate isn't 1.0 yet, so "anything goes" right :stuck_out_tongue:?

Feel free to ask if you have any more questions.  I've done quite a bit of work trying to get Bincode safe to use and I think this is the only robust way to do it.

**Comment by alexcrichton** [comment]
Hm ok, thanks for the explanation! The only thing I'm left wondering is that if `len != capacity`, you're still expected to call the `read_seq_elt` function `len` times, so is the idea that if `len` is corrupted then at some point it'll hit an I/O error of some form? It seems like you could still have some form of CPU exhaustion with a very-high length even if you don't have memory exhaustion, but I may be missing something.

>  Besides, the crate isn't 1.0 yet, so "anything goes" right?

Yeah I definitely agree that in theory we can make any change we'd like to this crate, but in reality these sorts of changes carry with them a cost. I'd be fine releasing a 0.4 of this crate, but it'd probably want a few more goodies if possible other than just this one change unfortunately :(

**Comment by TyOverby** [comment]
> The only thing I'm left wondering is that if len != capacity, you're still expected to call the read_seq_elt function len times, so is the idea that if len is corrupted then at some point it'll hit an I/O error of some form?

Yeah basically.  Bincode also has a [SizeLimit](http://tyoverby.com/bincode/bincode/enum.SizeLimit.html) option for encoding and decoding that will fail when encoding or decoding or decoding a message that is over `n` wire-bytes long.  The docs that I linked are pretty thorough in the explanation of how it works in Bincode as well as the problem that it aims to solve.

It's really easy to stop floods (even with just a `.as_mut().take(MAX_MSG_SIZE)`), but it's basically impossible to stop the OOM error without changing this crate.

I'm fine with waiting until more breaking changes are queued up, but could we put a maximum wait time one it?  Like "if nothing else shows up in a month, we merge and bump the version"?

**Comment by alexcrichton** [comment]
> but it's basically impossible to stop the OOM error without changing this crate.

Can't the decoder also just generate an error when `read_seq` is called and it'd pass in a `len` which could possibly go over the maximum message size?

> I'm fine with waiting until more breaking changes are queued up, but could we put a maximum wait time one it? Like "if nothing else shows up in a month, we merge and bump the version"?

This feels like it's niche enough that it wouldn't require a major version bump on its own, but we could look more into this if it comes to that, yes.

**Comment by TyOverby** [comment]
> Can't the decoder also just generate an error when read_seq is called and it'd pass in a len which could possibly go over the maximum message size?

You can estimate, yes, but it isn't possible to do accurately in all cases.  `read_seq` can't find out  how big the `seq_elt` is (either on the wire OR in memory), and if you wanted to restrict on-wire-size, you can't have a single size value for that because enums variants of the same enum can have differing wire-sizes (though a similar memory size).

**Comment by alexcrichton** [comment]
Sure you can't be 100% accurate, but if a sequence says that it has 2^64-1 messages following you can pretty safely assume that's impossible. It seems like whatever the decoder would pass in as the capacity for a sequence would just be the maximum length if you want to be sensitive to user input (and if the specified length is greater than the max cap you just return an error)

**Comment by TyOverby** [comment]
I'd like for the boundary for "assume it's not possible" to be configurable by the user, and it seems like a huge hassle for the encoder and decoder to configure `Vec<Vec<T>>` where the top `Vec` has a different max-amount than the bottom `Vec`.  Any solution to this comes out seeming like a hack :(

**Comment by TyOverby** [comment]
Until this current change is satisfiable, I've made another patch here: https://github.com/rust-lang/rustc-serialize/pull/122 that will make rustc-serialize never call `with_capacity` for collections.  This will obviously stop the OOM bug, but at the cost of performance.

**Comment by alexcrichton** [comment]
I [commented in #122](https://github.com/rust-lang/rustc-serialize/pull/122#issuecomment-113934970), but I feel like that isn't the best solution to this problem. 

>  Any solution to this comes out seeming like a hack :(

Would rejecting all vectors with > 4 billion elements "solve" this problem? It sounds like you have some logic to pass the expected capacity separately from the expected length, but I'm failing to see how if the length exceeds that capacity that it shouldn't have just been rejected in the first place.

**Comment by TyOverby** [comment]
> Would rejecting all vectors with > 4 billion elements "solve" this problem?

Not for a pathological case.  Imagine I have a game server that is accepting TCP connections on a public port.  Now you can get get thousands of connections each requiring exactly a 4 billion element arrays.   I'm not sure what would happen on every OS with regards to eagerly fetching that much memory, but it's something that I'd like to prevent.

Plus, having a 4-billion `u8`'s is very different from 4-billion `[u8; 256]`.

> I'm failing to see how if the length exceeds that capacity that it shouldn't have just been rejected in the first place.

I see this happening all the time!  Because the "lengths" that are passed in are completely untrusted and unverifiable, the decoder should make a *very* conservative estimate for the capacity.  Even something simple like `capacity = min(1024, untrusted_length)`.

**Comment by TyOverby** [comment]
> I commented in #122, but I feel like that isn't the best solution to this problem.

Neither do I, but I intended it as a non-breaking change that would fix this issue until a breaking change could land.

**Comment by alexcrichton** [comment]
> Plus, having a 4-billion u8's is very different from 4-billion [u8; 256].

I somewhat disagree with this as each type has a known static size that you'd be preallocating for, and it's pretty safe to assume there's some constant for each application, so you'd just do something like limit the maximum length by 4 billion / maximum type size in an array, which should still be *quite* lenient.

>  Even something simple like capacity = min(1024, untrusted_length).

This seems like a plausible course of action for *now*.

**Comment by alexcrichton** [comment]
superseded by https://github.com/rust-lang-nursery/rustc-serialize/pull/150

**Pull request closed without merging**
